# This is a basic workflow to help you get started with Actions

name: Publish to Maven Central

# Triggers the workflow on manually
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | gpg --batch --import
        gpg --export-secret-keys >~/.gnupg/secring.gpg
        gpg --list-secret-keys --keyid-format LONG

    - name: Publish release
      env:
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      run: |
        ./gradlew -Psigning.secretKeyRingFile=.gnupg/secring.gpg -Psigning.password="" -P signing.keyId=${{ secrets.GPG_KEY_ID }} publish

# Next, go to https://oss.sonatype.org/index.html#stagingRepositories, select the repo, "Close" it and then
# "Release" it
